vim.keymap.set({"n", "v"}, "H", "_")
vim.keymap.set({"n", "v"}, "L", "$")
vim.keymap.set("i", "jk", "<Esc>")
vim.keymap.set("n", "<leader>w", ":w<CR>")

vim.keymap.set("n", "<A-k>", ":m .-2<CR>==")
vim.keymap.set("n", "<A-j>", ":m .+1<CR>==")
vim.keymap.set("v", "<A-k>", ":m '<-2<CR>gv=gv")
vim.keymap.set("v", "<A-j>", ":m '>+1<CR>gv=gv")
vim.keymap.set("i", "<A-k>", "<Esc>:m .-2<CR>==gi")
vim.keymap.set("i", "<A-j>", "<Esc>:m .+1<CR>==gi")

vim.keymap.set("n", "J", "mZJ`Z")
vim.keymap.set("n", "<C-d>", "<C-d>zz")
vim.keymap.set("n", "<C-u>", "<C-u>zz")
vim.keymap.set("n", "n", "nzzzv")
vim.keymap.set("n", "N", "Nzzzv")

vim.keymap.set("n", "<leader>Y", '"+yg_')
vim.keymap.set({"n", "v"}, "<leader>y", '"+y')
vim.keymap.set({"n", "v"}, "<leader>p", '"+p')
vim.keymap.set({"n", "v"}, "<leader>P", '"+P')
vim.keymap.set({"n", "v"}, "<leader>d", '"_d')

vim.keymap.set("n", "]p", 'o<Esc>p')
vim.keymap.set("n", "[p", 'O<Esc>p')
vim.keymap.set("n", "<leader>]p", 'o<Esc>"+p')
vim.keymap.set("n", "<leader>[p", 'O<Esc>"+p')
