format = """
[](#5e81ac)\
$os\
[](bg:#81a1c1 fg:#5e81ac)\
$directory\
[](bg:#88c0d0 fg:#81a1c1)\
$git_branch$git_commit$git_state$git_status\
[](bg:#8fbcbb fg:#88c0d0)\
$package$c$cmake$cobol$daml$dart$deno$dotnet$elixir$elm$erlang$fennel$gleam\
$golang$guix_shell$haskell$haxe$helm$java$julia$kotlin$gradle$lua$nim$nodejs\
$ocaml$opa$perl$php$pulumi$purescript$python$quarto$raku$rlang$red$ruby$rust\
$scala$solidity$swift$terraform$typst$vlang$vagrant$zig\
[](bg:#d9dee9 fg:#8fbcbb)\
$cmd_duration\
[](fg:#d9dee9)\
$line_break\
$character
"""

[git_branch]
format = "[ $symbol$branch(:$remote_branch) ]($style)"
symbol = "󰘬 "
style = "fg:#2e3440 bg:#88c0d0"

[git_commit]
style = "fg:#2e3440 bg:#88c0d0"

[git_state]
style = "fg:#2e3440 bg:#88c0d0"

[git_status]
style = "fg:#2e3440 bg:#88c0d0"

# LANGUAGES
# =========

[lua]
symbol = '󰢱 '
format = '[ $symbol($version )]($style)'
style = "fg:#2e3440 bg:#8fbcbb"

[python]
symbol = '󰌠 '
format = "[ $symbol($version )]($style)"
style = "fg:#2e3440 bg:#8fbcbb"

# MISC
# ====

[hostname]
ssh_only = false
style = "fg:#2e3440 bg:#5e81ac"
format = "[$ssh_symbol$hostname ]($style)"
ssh_symbol = " "

[os]
style = "fg:#2e3440 bg:#5e81ac"
disabled = false

[os.symbols]
Arch = ' '

[shell]
disabled = false

[username]
show_always = true
format = '[$user]($style)'
style_user = "fg:#2e3440 bg:#5e81ac"

[directory]
style = "fg:#2e3440 bg:#81a1c1"
read_only = " "
format = "[ 󰉋 $path ]($style)[$read_only]($read_only_style)"
read_only_style = "fg:#2e3440 bold bg:#81a1c1"

[sudo]
disabled = false
symbol = " "
style = "fg:#2e3440 bg:#d9dee9"
format = "[ $symbol]($style)"

[cmd_duration]
format = "[ 󰔚 $duration ]($style)"
style = "fg:#2e3440 bg:#d9dee9"

[character]
success_symbol = "[ 󱞩](bold green)"
error_symbol = "[ 󱞩](bold red)"
vimcmd_symbol = "[  󱞩](bold green)"
